"""Persistence layer protocol interfaces."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from .models import HistoryEntryData, ProgressData, SettingData, TopicData


@runtime_checkable
class DatabasePort(Protocol):
    """High-level database lifecycle contract.

    Future consumers depend on this protocol rather than on
    ``DatabaseManager`` directly.
    """

    def initialize(self) -> None: ...

    def close(self) -> None: ...

    def health_check(self) -> bool: ...

    def version(self) -> int: ...


@runtime_checkable
class TransactionManagerPort(Protocol):
    """Transaction boundary contract."""

    def begin(self) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...


@runtime_checkable
class UnitOfWorkPort(Protocol):
    """Context-managed transaction boundary."""

    connection: Any

    def __enter__(self) -> UnitOfWorkPort: ...

    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...


# ── Repository protocol interfaces ────────────────────────────────────


@runtime_checkable
class TopicRepositoryPort(Protocol):
    """CRUD contract for topic persistence."""

    def get_all(self) -> list[TopicData]: ...
    def get_by_id(self, topic_id: str) -> TopicData | None: ...
    def get_by_category(self, category: str) -> list[TopicData]: ...
    def upsert(self, topic: TopicData) -> None: ...
    def delete(self, topic_id: str) -> bool: ...
    def count(self) -> int: ...


@runtime_checkable
class ProgressRepositoryPort(Protocol):
    """CRUD contract for progress persistence."""

    def get_by_topic(self, topic_id: str) -> ProgressData | None: ...
    def get_all(self) -> list[ProgressData]: ...
    def upsert(self, progress: ProgressData) -> None: ...
    def delete_by_topic(self, topic_id: str) -> bool: ...
    def count(self) -> int: ...
    def get_completed_count(self) -> int: ...


@runtime_checkable
class SettingsRepositoryPort(Protocol):
    """CRUD contract for settings persistence."""

    def get(self, key: str) -> SettingData | None: ...
    def get_all(self) -> list[SettingData]: ...
    def set(self, key: str, value: str) -> None: ...
    def delete(self, key: str) -> bool: ...
    def count(self) -> int: ...


@runtime_checkable
class HistoryRepositoryPort(Protocol):
    """CRUD contract for chat history persistence."""

    def get_by_session(self, session_id: str) -> list[HistoryEntryData]: ...
    def get_by_topic(self, topic_id: str) -> list[HistoryEntryData]: ...
    def add(self, entry: HistoryEntryData) -> None: ...
    def delete_by_session(self, session_id: str) -> bool: ...
    def delete_older_than(self, before: str) -> int: ...
    def count(self) -> int: ...
